### ISSUE TITLE
A bug when training CP+linear

### ISSUE THREAD

**Issue by ljh0v0** [YatingMusic/compound-word-transformer#4]
I'm working on something related to computer music these days and notice your compelling work. However, when I downloaded your source code and tried to run the model, I got this error.

```
num of classes: [56, 135, 18, 3, 87, 18, 25]
>>>>>: [56, 135, 18, 3, 87, 18, 25]
n_parameters: 39,016,630
     num_batch: 406
    train_x: (1625, 3584, 7)
    train_y: (1625, 3584, 7)
    train_mask: (1625, 3584)
Traceback (most recent call last):
  File "D:/Documents/科研/computer music/baseline/compound-word-transformer-main/compound-word-transformer-main/workspace/uncond/cp-linear/main-cp.py", line 711, in <module>
    train()
  File "D:/Documents/科研/computer music/baseline/compound-word-transformer-main/compound-word-transformer-main/workspace/uncond/cp-linear/main-cp.py", line 586, in train
    losses = net.train_step(batch_x, batch_y, batch_mask)
  File "D:/Documents/科研/computer music/baseline/compound-word-transformer-main/compound-word-transformer-main/workspace/uncond/cp-linear/main-cp.py", line 302, in train_step
    h, y_type  = self.forward_hidden(x)
  File "D:/Documents/科研/computer music/baseline/compound-word-transformer-main/compound-word-transformer-main/workspace/uncond/cp-linear/main-cp.py", line 367, in forward_hidden
    h = self.transformer_encoder(pos_emb, attn_mask) # y: b x s x d_model
  File "C:\Users\liujiahe\anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\liujiahe\anaconda3\envs\pytorch\lib\site-packages\fast_transformers\transformers.py", line 138, in forward
    x = layer(x, attn_mask=attn_mask, length_mask=length_mask)
  File "C:\Users\liujiahe\anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\liujiahe\anaconda3\envs\pytorch\lib\site-packages\fast_transformers\transformers.py", line 77, in forward
    x = x + self.dropout(self.attention(
  File "C:\Users\liujiahe\anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\liujiahe\anaconda3\envs\pytorch\lib\site-packages\fast_transformers\attention\attention_layer.py", line 103, in forward
    new_values = self.inner_attention(
  File "C:\Users\liujiahe\anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\liujiahe\anaconda3\envs\pytorch\lib\site-packages\fast_transformers\attention\causal_linear_attention.py", line 98, in forward
    V = causal_linear(
  File "C:\Users\liujiahe\anaconda3\envs\pytorch\lib\site-packages\fast_transformers\attention\causal_linear_attention.py", line 23, in causal_linear
    V_new = causal_dot_product(Q, K, V)
  File "C:\Users\liujiahe\anaconda3\envs\pytorch\lib\site-packages\fast_transformers\causal_product\__init__.py", line 44, in forward
    CausalDotProduct.dot[device.type](
TypeError: 'NoneType' object is not callable
```

I used the AILabs.tw Pop17K dataset you provide and changed nothing but the path. I can't figure out what's wrong. Hope you can help me. Thank you!

**Comment by wayne391** [comment]
Hi, it seems the bug comes from the `fast_transformers` package. Could you provide the version?
According [here](https://colab.research.google.com/drive/1AU8iMhy10WxHj7yt3j8S3FQvvKvgXrr0#scrollTo=y-2tfLtmNQHl), the version is` pytorch-fast-transformers-0.3.0`.

**Comment by ljh0v0** [comment]
Yeah. My version is `pytorch-fast-transformers 0.4.0`. 
After I replaced it with version 0.3.0, it worked. Thank you!

**Comment by EpochKC** [comment]
Thanks for your great work!  I still got a similar error after changed the `pytorch-fast-transformers 0.4.0 `to version 0.3.0.
Here is my environment,
`python 3.6.9`
`cuda 10.2`
`pytorch 1.8.1`
`pytorch-fast-transformers 0.3.0 `

Dataset:
AILabs.tw Pop17K 

```
Traceback (most recent call last):
  File "main-cp.py", line 711, in <module>
    train()
  File "main-cp.py", line 586, in train
    losses = net.train_step(batch_x, batch_y, batch_mask)
  File "main-cp.py", line 302, in train_step
    h, y_type  = self.forward_hidden(x)
  File "main-cp.py", line 367, in forward_hidden
    h = self.transformer_encoder(pos_emb, attn_mask) # y: b x s x d_model
  File "/home/kurt/Task/Env/env-cp-t/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/kurt/Task/Env/env-cp-t/lib/python3.6/site-packages/pytorch_fast_transformers-0.3.0-py3.6-linux-x86_64.egg/fast_transformers/transformers.py", line 139, in forward
    x = layer(x, attn_mask=attn_mask, length_mask=length_mask)
  File "/home/kurt/Task/Env/env-cp-t/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/kurt/Task/Env/env-cp-t/lib/python3.6/site-packages/pytorch_fast_transformers-0.3.0-py3.6-linux-x86_64.egg/fast_transformers/transformers.py", line 81, in forward
    key_lengths=length_mask
  File "/home/kurt/Task/Env/env-cp-t/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/kurt/Task/Env/env-cp-t/lib/python3.6/site-packages/pytorch_fast_transformers-0.3.0-py3.6-linux-x86_64.egg/fast_transformers/attention/attention_layer.py", line 109, in forward
    key_lengths
  File "/home/kurt/Task/Env/env-cp-t/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/kurt/Task/Env/env-cp-t/lib/python3.6/site-packages/pytorch_fast_transformers-0.3.0-py3.6-linux-x86_64.egg/fast_transformers/attention/causal_linear_attention.py", line 101, in forward
    values
  File "/home/kurt/Task/Env/env-cp-t/lib/python3.6/site-packages/pytorch_fast_transformers-0.3.0-py3.6-linux-x86_64.egg/fast_transformers/attention/causal_linear_attention.py", line 23, in causal_linear
    V_new = causal_dot_product(Q, K, V)
  File "/home/kurt/Task/Env/env-cp-t/lib/python3.6/site-packages/pytorch_fast_transformers-0.3.0-py3.6-linux-x86_64.egg/fast_transformers/causal_product/__init__.py", line 48, in forward
    product
TypeError: 'NoneType' object is not callable
```

I noticed the pytorch version that in your colab is 1.7.0, so I changed the version of pytorch from 1.8.1 to 1.7.0, then I got the different error,

```
File "main-cp.py", line 22, in <module>
    from fast_transformers.builders import TransformerEncoderBuilder
  File "/home/kurt/Task/Env/env-cp-t/lib/python3.6/site-packages/pytorch_fast_transformers-0.3.0-py3.6-linux-x86_64.egg/fast_transformers/builders/__init__.py", line 42, in <module>
    from ..attention import \
  File "/home/kurt/Task/Env/env-cp-t/lib/python3.6/site-packages/pytorch_fast_transformers-0.3.0-py3.6-linux-x86_64.egg/fast_transformers/attention/__init__.py", line 13, in <module>
    from .causal_linear_attention import CausalLinearAttention
  File "/home/kurt/Task/Env/env-cp-t/lib/python3.6/site-packages/pytorch_fast_transformers-0.3.0-py3.6-linux-x86_64.egg/fast_transformers/attention/causal_linear_attention.py", line 15, in <module>
    from ..causal_product import causal_dot_product
  File "/home/kurt/Task/Env/env-cp-t/lib/python3.6/site-packages/pytorch_fast_transformers-0.3.0-py3.6-linux-x86_64.egg/fast_transformers/causal_product/__init__.py", line 9, in <module>
    from .causal_product_cpu import causal_dot_product as causal_dot_product_cpu, \
ImportError: /home/kurt/Task/Env/env-cp-t/lib/python3.6/site-packages/pytorch_fast_transformers-0.3.0-py3.6-linux-x86_64.egg/fast_transformers/causal_product/causal_product_cpu.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2at5zerosEN3c108ArrayRefIlEENS0_13TensorOptionsE
```
Hoping you can help me figure it out. Thank you!

**Comment by li-car-fei** [comment]
> Thanks for your great work! I still got a similar error after changed the `pytorch-fast-transformers 0.4.0 `to version 0.3.0. Here is my environment, `python 3.6.9` `cuda 10.2` `pytorch 1.8.1` `pytorch-fast-transformers 0.3.0 `
> 
> Dataset: AILabs.tw Pop17K
> 
> ```
> Traceback (most recent call last):
>   File "main-cp.py", line 711, in <module>
>     train()
>   File "main-cp.py", line 586, in train
>     losses = net.train_step(batch_x, batch_y, batch_mask)
>   File "main-cp.py", line 302, in train_step
>     h, y_type  = self.forward_hidden(x)
>   File "main-cp.py", line 367, in forward_hidden
>     h = self.transformer_encoder(pos_emb, attn_mask) # y: b x s x d_model
>   File "/home/kurt/Task/Env/env-cp-t/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "/home/kurt/Task/Env/env-cp-t/lib/python3.6/site-packages/pytorch_fast_transformers-0.3.0-py3.6-linux-x86_64.egg/fast_transformers/transformers.py", line 139, in forward
>     x = layer(x, attn_mask=attn_mask, length_mask=length_mask)
>   File "/home/kurt/Task/Env/env-cp-t/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "/home/kurt/Task/Env/env-cp-t/lib/python3.6/site-packages/pytorch_fast_transformers-0.3.0-py3.6-linux-x86_64.egg/fast_transformers/transformers.py", line 81, in forward
>     key_lengths=length_mask
>   File "/home/kurt/Task/Env/env-cp-t/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "/home/kurt/Task/Env/env-cp-t/lib/python3.6/site-packages/pytorch_fast_transformers-0.3.0-py3.6-linux-x86_64.egg/fast_transformers/attention/attention_layer.py", line 109, in forward
>     key_lengths
>   File "/home/kurt/Task/Env/env-cp-t/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "/home/kurt/Task/Env/env-cp-t/lib/python3.6/site-packages/pytorch_fast_transformers-0.3.0-py3.6-linux-x86_64.egg/fast_transformers/attention/causal_linear_attention.py", line 101, in forward
>     values
>   File "/home/kurt/Task/Env/env-cp-t/lib/python3.6/site-packages/pytorch_fast_transformers-0.3.0-py3.6-linux-x86_64.egg/fast_transformers/attention/causal_linear_attention.py", line 23, in causal_linear
>     V_new = causal_dot_product(Q, K, V)
>   File "/home/kurt/Task/Env/env-cp-t/lib/python3.6/site-packages/pytorch_fast_transformers-0.3.0-py3.6-linux-x86_64.egg/fast_transformers/causal_product/__init__.py", line 48, in forward
>     product
> TypeError: 'NoneType' object is not callable
> ```
> 
> I noticed the pytorch version that in your colab is 1.7.0, so I changed the version of pytorch from 1.8.1 to 1.7.0, then I got the different error,
> 
> ```
> File "main-cp.py", line 22, in <module>
>     from fast_transformers.builders import TransformerEncoderBuilder
>   File "/home/kurt/Task/Env/env-cp-t/lib/python3.6/site-packages/pytorch_fast_transformers-0.3.0-py3.6-linux-x86_64.egg/fast_transformers/builders/__init__.py", line 42, in <module>
>     from ..attention import \
>   File "/home/kurt/Task/Env/env-cp-t/lib/python3.6/site-packages/pytorch_fast_transformers-0.3.0-py3.6-linux-x86_64.egg/fast_transformers/attention/__init__.py", line 13, in <module>
>     from .causal_linear_attention import CausalLinearAttention
>   File "/home/kurt/Task/Env/env-cp-t/lib/python3.6/site-packages/pytorch_fast_transformers-0.3.0-py3.6-linux-x86_64.egg/fast_transformers/attention/causal_linear_attention.py", line 15, in <module>
>     from ..causal_product import causal_dot_product
>   File "/home/kurt/Task/Env/env-cp-t/lib/python3.6/site-packages/pytorch_fast_transformers-0.3.0-py3.6-linux-x86_64.egg/fast_transformers/causal_product/__init__.py", line 9, in <module>
>     from .causal_product_cpu import causal_dot_product as causal_dot_product_cpu, \
> ImportError: /home/kurt/Task/Env/env-cp-t/lib/python3.6/site-packages/pytorch_fast_transformers-0.3.0-py3.6-linux-x86_64.egg/fast_transformers/causal_product/causal_product_cpu.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2at5zerosEN3c108ArrayRefIlEENS0_13TensorOptionsE
> ```
> 
> Hoping you can help me figure it out. Thank you!

I have the same problem, have you solved it?
